version: '3.8'

services:
  my-deno-website:
    image: robertfent1/deno-website:latest
    container_name: my-deno-website
    ports:
      - $SERVER_PORT:$SERVER_PORT

volumes:
  mongodb:
  mongoconfig: