version: '3.8'

services:
  my-deno-website:
    image: robertfent1/deno-website:ci
    container_name: my-deno-website
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      - MODE=2

volumes:
  mongodb:
  mongoconfig: