name: Build and push docker image with tag

on:
  push:
    branches: [master, develop]

jobs:
  # duplicate to job in main workflow except name of .env
  push-image:
    runs-on: ${{ matrix.os }} # runs build on Ubuntu

    # only use one version on ubuntu but let strategy be there for maybe later changes
    strategy:
      matrix:
        deno: ["v1.11.3"]
        os: [ubuntu-latest]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # use dev .env for later pushing of image
      - name: Setup .env
        if: github.ref == 'refs/heads/develop'
        run: cp ./example_envs/.env_mongo_network_dev .env

      # use prod .env for later pushing of image
      - name: Setup .env
        if: github.ref == 'refs/heads/master'
        run: |
          cp ./example_envs/.env_mongo_network .env
      
      - name: Load .env
        uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env

      - name: Set $TAG environment variable
        run: echo "TAG=$(echo $TAG)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/deno-website:${{ env.TAG }}